var reporting_data = {"lemoncheesecake_version": "1.3.1", "report_version": 1.1, "start_time": "2020-03-14T16:29:56.993Z", "end_time": "2020-03-14T16:29:57.464Z", "generation_time": "2020-03-14T16:29:57.481Z", "nb_threads": 1, "title": "Test Report", "info": [["Command line", "lcc run firstsuite"]], "suites": [{"start_time": "2020-03-14T16:29:57.008Z", "end_time": "2020-03-14T16:29:57.464Z", "tests": [{"start_time": "2020-03-14T16:29:57.008Z", "end_time": "2020-03-14T16:29:57.009Z", "steps": [{"description": "test1", "start_time": "2020-03-14T16:29:57.008Z", "end_time": "2020-03-14T16:29:57.009Z", "entries": [{"type": "check", "description": "Expect value to be equal to 4.0", "is_successful": true, "details": "Got 4", "time": "2020-03-14T16:29:57.009Z"}]}], "status": "passed", "status_details": null, "name": "test1", "description": "test1", "tags": [], "properties": {}, "links": []}, {"start_time": "2020-03-14T16:29:57.009Z", "end_time": "2020-03-14T16:29:57.009Z", "steps": [], "status": "passed", "status_details": null, "name": "test2", "description": "test2", "tags": [], "properties": {}, "links": []}, {"start_time": "2020-03-14T16:29:57.010Z", "end_time": "2020-03-14T16:29:57.463Z", "steps": [{"description": "test3", "start_time": "2020-03-14T16:29:57.010Z", "end_time": "2020-03-14T16:29:57.463Z", "entries": [{"type": "check", "description": "Expect http code to be equal to 200", "is_successful": true, "details": "Got 200", "time": "2020-03-14T16:29:57.438Z"}, {"type": "log", "level": "error", "message": "Caught unexpected exception while running test: Traceback (most recent call last):\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\lemoncheesecake\\runner.py\", line 188, in run\n    self.test.callback(**test_func_params)\n  File \"C:\\Users\\atpc8\\sdlc\\lemontest\\suites\\firstsuite.py\", line 23, in test3\n    resp = r.json()\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\requests\\models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\json\\__init__.py\", line 348, in loads\n    return _default_decoder.decode(s)\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "time": "2020-03-14T16:29:57.463Z"}]}], "status": "failed", "status_details": null, "name": "test3", "description": "test3", "tags": [], "properties": {}, "links": []}], "suites": [], "name": "firstsuite", "description": "my_suite", "tags": ["samples", "tutorials"], "properties": {}, "links": []}]}